config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :articles

  get 'about', to: 'pages#about'
  get 'person', to: 'persons#gender'
  get 'rdsstart', to: 'skejulers#rdsstart'
  get 'rdsstop', to: 'skejulers#rdsstop'
  get 'ec2start', to: 'skejulers#ec2start'
  get 'ec2stop', to: 'skejulers#ec2stop'
  get 'start', to: 'startstopins#start'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 1000}
  validates :user_id, presence: true


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only:[:edit, :update, :show, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
     @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path (@article)
    else
    render 'new'
    end
  end
  def edit
  end
  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  def show
  end
  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end
  end
private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
  params.require(:article).permit(:title, :description)
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class = "row">
<div class = "col-xs-8 col-xs-offset-2">
<div class = "well well-lg">
<div class = "article-title">
    <%= link_to article.title, article_path(article) %>
</div>
<div class = "article-body" >
    <%= truncate(article.description) %>
    <div class = "article-meta-details">
    <small>Created by: <% article.user.username if article.user%>,
            <%= time_ago_in_words(article.created_at) %> ago,
            last updated: <%= time_ago_in_words(article.updated_at) %> ago </small>
    </div>
</div>
<% if logged_in? && current_user == article.user %>
  <div class = "article-actions" >
      <td><%= link_to "Edit", edit_article_path(article) %></td>
      <td><%= link_to 'Show', article_path(article) %> </td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are You Sure?"} %></td>
    </tr>
  </div>
<% end %>
</div>
</div>
</div>
  <% end %>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>The following errors prevented from saving</h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
      <% end %>
    </ul>
<% end %>

<div class="row">
  <div class="col-xs-12">

<%= form_for @article do |f| %>
     <div class="'form-group">
     <div class="control-label col-sm-12">
      <%= f.label :title %>
       </div>
       <div class="col-sm-8">
      <%= f.text_field :title, class:"form-control", placeholder: "Title of article", autofocus: true %>
         </div>
       </div>
        <div class = "form-group">
          <div class = "control-label col-sm-2">
      <%= f.label :description %>
            </div>
          <div class="col-sm-8">
      <%= f.text_area :description, rows:10,  class: "form-control", placeholder: "Body of Article"  %>
            </div>
          </div>
        <div class = "form-group" >
          <div class = "col -sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
<% end %>
<%= link_to " Go to Articles listing", articles_path %>

</div>
  </div>

app/views/articles/edit.html.erb
<h1>Edit this Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>

<p><%= link_to "Create New Article", new_article_path %></p>

<div align = "center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align = "center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

<% if @article.user %>

<ul class="listing">

<div class="row center">

<div class="col-md-4 col-md-offset-4">

<li>Created by:</li>

<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>

<li class="article-title">

<%= link_to @article.user.username, user_path(@article.user)%>

</li>

<li><small>

<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>

</small></li>

</div>

</div>

</ul>

<% end %>

<h4 class="center description"><strong>Description:</strong></h4>

<hr>

<%= simple_format(@article.description) %>

<div class="article-actions">

<% if logged_in? && current_user == @article.user %>

  <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
  <%= link_to "Delete this article", article_path(@article), method: :delete,
  data: { confirm: "Are you sure you want to delete the article?"},
  class: "btn btn-xs btn-danger" %>

<% end %>

<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

</div>

</div>