config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :articles

  get 'about', to: 'pages#about'
  get 'person', to: 'persons#gender'
  get 'rdsstart', to: 'skejulers#rdsstart'
  get 'rdsstop', to: 'skejulers#rdsstop'
  get 'ec2start', to: 'skejulers#ec2start'
  get 'ec2stop', to: 'skejulers#ec2stop'
  get 'start', to: 'startstopins#start'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class ="footer">
    <small>
      copyright &copy <a href="http://www.nagahota.com">Naga Hota</a>
    </small>
    <nav>
      <ul>
        <li> <%= link_to "About", about_path %> </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<!-- <% flash.each do |name,msg| %>
    <ul>
      <li> <%= msg %> </li>
    </ul>
<% end %> -->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>

        <% if logged_in? %>

        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Articles <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path%></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Your profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'SignUP', signup_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>